service: calculator-api
frameworkVersion: '3'

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.9
  environment:
    USER_TABLE:
      Ref: UserTable
    OPERATION_TABLE:
      Ref: OperationTable
    RECORD_TABLE:
      Ref: RecordTable
    LOGGER_SERVICE_NAME: ${self:service}-logger
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:DescribeTable
          Resource: "*"

functions:
  hello:
    handler: src.handler.hello.handler
    events:
      - httpApi:
          path: /
          method: get
resources:
  Resources:
    UserTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: username
            AttributeType: S
          - AttributeName: password
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: username_password_index
            KeySchema:
              - AttributeName: username
                KeyType: HASH
              - AttributeName: password
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

    OperationTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: operation_id
            AttributeType: S
        KeySchema:
          - AttributeName: operation_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    RecordTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: record_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: operation_id
            AttributeType: S
        KeySchema:
          - AttributeName: record_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: user_index
            KeySchema:
              - AttributeName: user_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
